### PR TITLE
Removing unnecessary console.logs

### PR DESCRIPTION
**Pull request by kennyczadzeck**
Removing a couple unnecessary console.logs that were missed during prior code reviews.

### CODE REVIEW

**Comment by kennyczadzeck** [comment]
NOTE - compare these changes with upcoming Angular routes pull request from Module team before merging. They might have fixed the same issues.

**Comment by kennyczadzeck** [comment]
Removed layout.ejs from commit/pull request

**Comment by kennyczadzeck** [comment]
Just added repairs to fix code highlighting in student lesson view.

**Comment by delasky** [comment]
squash these two into once commit and i will merge

**Pull request merged**
