### PR TITLE
Library angular

### PR DESCRIPTION
**Pull request by Conroyce**
Create view for library, can create new modules

### CODE REVIEW

**Comment by xoddong** [comment]
APPROVED!

**Comment by seangibat** [comment]
Looks good. :100: :wink:

**Comment by Dudemullet** [comment]
@Conroyce Could you be a bit more descriptive in your pull request description so I know what this Pull request is doing please? Otherwise I don't know what to test.

**Comment by Dudemullet** [comment]
:+1:  Please squash so I can merge

**Pull request merged**
